CREATE TABLE clientes (
                          id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                          nome  VARCHAR(255),
                          email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE transportadoras (
                                 id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                 nome       VARCHAR(255),
                                 frete_fixo DECIMAL
);

CREATE TABLE produtos (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                          nome           VARCHAR(255),
                          descricao      VARCHAR(255),
                          preco_unitario DECIMAL,
                          estoque        INTEGER,
                          ativo          BOOLEAN
);

CREATE TABLE carrinhos (
                           id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                           cliente_id   BIGINT NOT NULL,
                           status       VARCHAR(255),
                           data_criacao TIMESTAMP WITHOUT TIME ZONE,
                           CONSTRAINT fk_carrinho_cliente FOREIGN KEY(cliente_id) REFERENCES clientes(id)
);

CREATE TABLE enderecos (
                           id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                           cliente_id   BIGINT,
                           rua          VARCHAR(255),
                           numero       VARCHAR(255),
                           complemento  VARCHAR(255),
                           bairro       VARCHAR(255),
                           cidade       VARCHAR(255),
                           estado       VARCHAR(255),
                           cep          VARCHAR(255),
                           pais         VARCHAR(255),
                           is_principal BOOLEAN,
                           CONSTRAINT fk_endereco_cliente FOREIGN KEY(cliente_id) REFERENCES clientes(id)
);

CREATE TABLE pedidos (
                         id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                         cliente_id          BIGINT NOT NULL,
                         carrinho_entrega_id BIGINT NOT NULL,
                         transportadora_id   BIGINT NOT NULL,
                         frete               DECIMAL,
                         forma_pagamento     VARCHAR(255),
                         valor_total         DECIMAL,
                         data_pedido         TIMESTAMP WITHOUT TIME ZONE,
                         status              VARCHAR(255),
                         CONSTRAINT fk_pedido_cliente FOREIGN KEY(cliente_id) REFERENCES clientes(id),
                         CONSTRAINT fk_pedido_endereco FOREIGN KEY(carrinho_entrega_id) REFERENCES enderecos(id),
                         CONSTRAINT fk_pedido_transportadora FOREIGN KEY(transportadora_id) REFERENCES transportadoras(id)
);

CREATE TABLE item_carrinho (
                               id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                               carrinho_id    BIGINT NOT NULL,
                               produto_id     BIGINT NOT NULL,
                               quantidade     INTEGER,
                               preco_unitario DECIMAL,
                               CONSTRAINT fk_itemcarrinho_carrinho FOREIGN KEY(carrinho_id) REFERENCES carrinhos(id),
                               CONSTRAINT fk_itemcarrinho_produto FOREIGN KEY(produto_id) REFERENCES produtos(id)
);

CREATE TABLE item_pedido (
                             id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                             pedido_id      BIGINT NOT NULL,
                             produto_id     BIGINT NOT NULL,
                             quantidade     INTEGER,
                             preco_unitario DECIMAL,
                             CONSTRAINT fk_itempedido_pedido FOREIGN KEY(pedido_id) REFERENCES pedidos(id),
                             CONSTRAINT fk_itempedido_produto FOREIGN KEY(produto_id) REFERENCES produtos(id)
);

-- habilita extensão de UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE notas_fiscais (
                               id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                               pedido_id    BIGINT NOT NULL UNIQUE,
                               numero       VARCHAR(255) NOT NULL UNIQUE,
                               data_emissao TIMESTAMP WITHOUT TIME ZONE,
                               json_nota    TEXT,
                               CONSTRAINT fk_notafiscal_pedido FOREIGN KEY(pedido_id) REFERENCES pedidos(id)
);
